### ISSUE TITLE
New SOIC8 board adapter

### ISSUE THREAD

**Issue by siro20** [felixheld/qspimux#1]
The existing SOIC-8 board adapter is difficult to solder. It would be nice to have a smaller PCB and bigger pads below.

**Comment by felixheld** [comment]
I'll decrease the width of the PCB, so that you can solder it more easily; I can increase the diameter of the castellated holes only by about 0.1mm though, since I'm rather close to the minimum distance in the pcbway design rules. The diameter of the castellated holes is already below their recommended minimum diameter, but I made sure that they are able to manufacture that. Oh and the boards only have castellated holes without edge plating, because the additional cost for edge plating would have massively increased the price (IIRC by a factor of ~6 for that board).
I'm planning to tweak the board adapter design a bit, but it is constrained by what can be done on a reasonably priced manufacturing process.

**Comment by felixheld** [comment]
Ordering a thinner (0.6mm instead of 1.6mm) version of the board adapter improved the aspect ratio of the castellated holes and solved the solderability issue for me.

**Comment by felixheld** [comment]
The 0.6mm thin SOIC8W board adapter works much better than the 1.6mm ones, so I'll close this bug, since I also don't see improvements that wouldn't massively increase the manufacturing cost here. Feel free to reopen if the thinner board adapters don't work for you.
